version: "3"
services:
  app:
    container_name: flask_app
    restart: unless-stopped
    build: ./src/
    depends_on:
      - mysql
    ports:
      - '5000:5000'
    networks:
      - my_network

  mysql:
    container_name: flask_mysql
    restart: always
    build: ./db/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_HOST: mysql
    ports:
      - '3307:3306'
    networks:
      - my_network

networks:
 my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
