version: "3"

services:
 app:
    image: "flask_app:latest"
    container_name: flask_app
    env_file:
      - .env
    restart: unless-stopped
    build: ./src/
    depends_on:
      - mysql
    ports:
      - '5000:5000'
    networks:
      - my_network

 mysql:
    image: "mysql:latest"
    container_name: flask_mysql
    restart: always
    build: ./db/
    env_file:
      - .env
    ports:
      - '3307:3306'
    networks:
      - my_network

networks:
 my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16