version: "3"
services:
  app:
    image: "flask_app:latest"
    container_name: flask_app
    environment:
      - DOCKERIZED=true
    restart: unless-stopped
    build: ./src/
    depends_on:
     - mysql
    ports:
     - '5000:5000'

  mysql:
    image: "mysql:latest"
    container_name: flask_mysql
    restart: always
    build: ./db/
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'project'
      MYSQL_HOST: 'mysql'
    ports:
      - '3307:3306'
