version: "3"
services:
  app:
    image: "flask_app:latest"
    container_name: flask_app
    restart: unless-stopped
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: project
    depends_on:
     - mysql
    ports:
     - "5000:5000"

  mysql:
    image: "mysql:latest"
    container_name: flask_mysql
    restart: always
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - db_data_config:/etc/mysql

volumes:
  db_data:
  db_data_config: