version: "3"
services:
  app:
    image: "flask_app:latest"
    container_name: flask_app
    restart: unless-stopped
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: project
    links:
     - mysql
    depends_on:
     - mysql
    ports:
     - "5000:5000"

  mysql:
    container_name: flask_mysql
    image: "mysql:latest"
    volumes:
     - ./mysql:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_USER: root

