name: CD

on:
  workflow_run:
    workflows: CI
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.A_A_K }}
        aws-secret-access-key: ${{ secrets.A_S_A_K }}
        aws-region: us-east-1

    - name: Initialize Terraform
      working-directory: ./terraform
      run: terraform init

    - name: Plan Terraform
      working-directory: ./terraform
      run: terraform plan

    - name: Apply Terraform
      working-directory: ./terraform
      run: terraform apply -auto-approve

    - name: Upload artifact for CD
      uses: actions/upload-artifact@v2
      with:
        name: trigger-cd
        path: |
          ./src/
          ./db/
          ./terraform/
