name: CI

on: push

jobs:
 test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./src/requirements.txt

    - name: Start Services with Docker Compose
      run: docker-compose up -d

    - name: Add .env file
      run: |
        echo "${{ secrets.ENV_FILE }}" > $GITHUB_WORKSPACE/.env

    - name: Run Pytest
      run: pytest

    - name: Remove .env file
      run: rm $GITHUB_WORKSPACE/.env

    - name: Shutdown Docker Compose
      run: docker-compose down
