# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
 push:
    branches: [ "main" ]
 pull_request:
    branches: [ "main" ]

permissions:
 contents: read

jobs:
 build:

    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: project
        ports: ['3306:3306']
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install pytest
        pip install -r ./src/requirements.txt
    - name: Load MySQL data
      run: |
            while ! mysqladmin ping -h"localhost" -uroot -p"root"; do
             echo "Waiting for MySQL..."
             sleep 5
            done
            cat db/mysql.sql | mysql -h localhost -u root -proot project
    - name: Run tests
      run: |
        export TESTING=true
        pytest test/
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
   
