name: CI

on:
 push:
    branches: [ "main"]

jobs:
 check_docker_compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Docker Compose File
        run: docker-compose config

      - name: Start services with Docker Compose
        run: docker-compose up -d

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./src/requirements.txt 

      - name: Wait
        run: sleep 10

      - name: Run tests
        run: |
          pytest test/

      - name: Shutdown Docker Compose
        run: docker-compose down;
