name: CI

on: push

jobs:
 test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./src/requirements.txt

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Start Services with Docker Compose
      run: docker-compose up -d

    - name: Add .env file
      run: |
        echo "${{ secrets.ENV_FILE }}" > $GITHUB_WORKSPACE/.env

    - name: Wait
      run: sleep 20

    - name: Run Pytest
      run: pytest

    - name: Remove .env file
      run: rm $GITHUB_WORKSPACE/.env

    - name: Shutdown Docker Compose
      run: docker-compose down

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.LIOR_A_K }}
        aws-secret-access-key: ${{ secrets.LIOR_S_A_K }}
        aws-region: us-east-1

    - name: Login to Amazon ECR Public
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/v4y2i9y6

    - name: Build and push App Docker image to Amazon ECR Public
      run: |
        docker build -t public.ecr.aws/v4y2i9y6/project:app ./src/
        docker push public.ecr.aws/v4y2i9y6/project:app

    - name: Build and push DB Docker image to Amazon ECR Public
      run: |
        docker build -t public.ecr.aws/v4y2i9y6/project:db ./db/
        docker push public.ecr.aws/v4y2i9y6/project:db




