name: CI

on:
 push:

jobs:
 check_docker_compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Docker Compose File
        run: docker-compose config

      - name: Start services with Docker Compose
        run: docker-compose up -d

 copy_files_and_run_tests:
    needs: check_docker_compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy files
        run: |
          mkdir test_directory
          cp -r db src test .env test_directory/

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./src/requirements.txt 

      - name: Start MySQL Container
        run: docker-compose up -d mysql

      - name: Run tests
        run: |
          cd test_directory
          pytest test/

 shutdown_services:
    needs: copy_files_and_run_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Shutdown Docker Compose
        run: docker-compose down
