name: Python application

on:
 push:
    branches: [ "main" ]
 pull_request:
    branches: [ "main" ]

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Start services
      run: docker-compose up -d
    - name: Run tests
      run: |
        export TESTING=true
        pytest test/
    - name: Stop services
      run: docker-compose down
