jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: user/app:latest
    - name: Start services
      run: docker-compose up -d
    - name: Run tests
      run: |
        export TESTING=true
        pytest test/
    - name: Stop services
      run: docker-compose down
