name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: your_database_name
          MYSQL_USER: your_mysql_user
          MYSQL_PASSWORD: your_mysql_password

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10 and Docker Compose
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and run containers
      run: docker-compose up --build -d
      working-directory: .

    - name: Install dependencies
      run: python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r ./src/requirements.txt
    - name: Lint with flake8

      working-directory: .

    - name: Lint with flake8
      run: docker-compose exec app flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
      working-directory: .

    - name: Test with pytest
      run: docker-compose exec app pytest test/
      working-directory: .

    - name: Stop containers
      run: docker-compose down
      working-directory: .
