jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: project
        ports:
          - '3306:3306'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./src/requirements.txt

      - name: Get MySQL service IP address
        id: mysql_ip
        run: echo "::set-output name=IP::$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' db)"

      - name: Load MySQL data
        run: |
          cat db/mysql.sql | mysql -h ${{ steps.mysql_ip.outputs.IP }} -P 3306 -u root -proot project

      - name: Run tests
        run: |
          export TESTING=true
          pytest test/
