name: Test

on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

jobs:
 docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest mysql-connector-python flask

    - name: Start containers
      run: |
        docker-compose build --no-cache
        docker-compose up -d 

    - name: Run tests
      run: pytest

    - name: Stop containers
      if: always()
      run: docker-compose down

